-- Rebrand HappyDebt → Intro
--
-- This migration safely renames the SQL surface area that referenced
-- "happydebt": the admin function, the role enum value, and the leads
-- source enum value. RLS policies that call is_happydebt_admin() are
-- preserved automatically because Postgres stores the function OID,
-- not the name.
--
-- ⚠️ Run during a deploy window. Old code paths that hardcode
-- 'happydebt_admin' or 'happydebt' will fail until the new code is live.

BEGIN;

-- 1. Rename the admin check function. RLS policies that call
--    public.is_happydebt_admin() continue to work because Postgres
--    references the function by OID.
ALTER FUNCTION public.is_happydebt_admin() RENAME TO is_intro_admin;

-- 2. Migrate users.role data BEFORE changing the constraint.
UPDATE public.users
SET role = 'intro_admin'
WHERE role = 'happydebt_admin';

-- 3. Recreate users.role CHECK constraint with the new enum.
--    The original constraint name is generated by Postgres; drop by
--    expression match to be safe.
DO $$
DECLARE
  con_name text;
BEGIN
  SELECT conname INTO con_name
  FROM pg_constraint
  WHERE conrelid = 'public.users'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%role%';
  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.users DROP CONSTRAINT %I', con_name);
  END IF;
END $$;

ALTER TABLE public.users
  ADD CONSTRAINT users_role_check
  CHECK (role IN ('admin', 'manager', 'viewer', 'intro_admin'));

-- 4. Migrate leads.source data.
UPDATE public.leads
SET source = 'intro'
WHERE source = 'happydebt';

-- 5. Recreate leads.source CHECK and default.
DO $$
DECLARE
  con_name text;
BEGIN
  SELECT conname INTO con_name
  FROM pg_constraint
  WHERE conrelid = 'public.leads'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%source%';
  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.leads DROP CONSTRAINT %I', con_name);
  END IF;
END $$;

ALTER TABLE public.leads
  ADD CONSTRAINT leads_source_check
  CHECK (source IN ('intro', 'client_upload', 'ghl_sync'));

ALTER TABLE public.leads ALTER COLUMN source SET DEFAULT 'intro';

COMMIT;
