-- Cleanup: reduce 9 orgs to 2 (Rise + Intro) and move staff user to Intro.
-- Additionally: add invite_token column for shareable signup links.
--
-- Pre-conditions verified against production:
-- - Only 1 user exists (vicente@happydebt.com) in bd4ebe6e (Rise / rise-2xpi)
-- - Only bd4ebe6e has data (12,483 lt, 27 calls, 146 closers, 12,483 leads)
-- - The 8 other orgs are completely empty across all tables
-- - The 27 call_recordings have lead_id=NULL and live_transfer_id=NULL
--   (drill-down will use contact_phone match instead)

BEGIN;

-- ── 1. Rename fc2ffd5b (HappyDebt / happydebt) → Intro / intro ────────
UPDATE public.organizations
SET name = 'Intro', slug = 'intro'
WHERE id = 'fc2ffd5b-3ce1-48d0-b2b1-d95aff44b0f7';

-- ── 2. Move vicente from Rise → Intro ────────────────────────────────
UPDATE public.users
SET org_id = 'fc2ffd5b-3ce1-48d0-b2b1-d95aff44b0f7'
WHERE email = 'vicente@happydebt.com';

-- ── 3. Delete the empty Rise/rise org (frees the 'rise' slug) ────────
DELETE FROM public.organizations
WHERE id = '7d10e7f3-72d6-4ccc-9bfc-100b8fa23b3d';

-- ── 4. Rename bd4ebe6e (Rise / rise-2xpi) → Rise / rise (clean slug) ─
UPDATE public.organizations
SET slug = 'rise'
WHERE id = 'bd4ebe6e-03c6-4832-991f-4fd6de6fa67e';

-- ── 5. Delete the 6 remaining empty duplicate orgs ───────────────────
DELETE FROM public.organizations
WHERE id IN (
  '94b38cc2-352c-46bb-acbb-8491e4b1704e',  -- HappyDebt / happydebt-ej7h
  'a02086db-ab1b-46fa-bf1d-e152992a40f1',  -- HappyDebt / happydebt-nyc3
  'f33b7b04-e325-42ed-882c-fea418e5cd52',  -- Rise / rise-jqwz
  '39af6bf8-033d-4ada-a3a0-cb540d7312f3',  -- HappyDebt / happydebt-y16e
  '75c8fcbb-15d7-46ee-b69e-544eff43ac51',  -- Rise / rise-fjjh
  '146a147f-773b-4664-878e-e279f4fae8f7'   -- Rise / rise-4kkn
);

-- ── 6. Empty the leads table (12,483 rows auto-generated by 00005) ───
-- These were auto-populated from live_transfers and don't represent
-- actual lead uploads. The leads table will be reserved for BYOL.
DELETE FROM public.leads;

-- ── 7. Add invite_token column for shareable signup links ────────────
ALTER TABLE public.organizations
ADD COLUMN IF NOT EXISTS invite_token text UNIQUE;

-- Backfill: each org gets a unique reusable token (128 bits of entropy)
UPDATE public.organizations
SET invite_token = encode(gen_random_bytes(16), 'hex')
WHERE invite_token IS NULL;

-- Index for fast lookup at signup time
CREATE INDEX IF NOT EXISTS idx_organizations_invite_token
ON public.organizations(invite_token);

COMMIT;
